add_newline = true # Whenever to add a newline between commands

format = '''
$directory$git_branch$git_status
$character'''

[directory]
style = 'white'
truncation_length = 8
truncation_symbol = '.../'

[git_branch]
symbol = 'ï˜ '

[character]
success_symbol = '[>](bold white)'
error_symbol = '[>](bold red)'
